;;; early-init.el --- Hell Emacs early initialization -*- lexical-binding: t; no-byte-compile: t; -*-

;; Copyright (C) 2026 petrolal <petrolalucas@gmail.com>
;;
;; Author: petrolal <petrolalucas@gmail.com>
;; URL: https://github.com/petrolal/hell-emacs
;; License: GPL-3.0-or-later
;;
;; This file is part of Hell Emacs.
;;
;; Hell Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; Hell Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is loaded before `package.el', before `init.el', and
;; before the first frame is created.  Everything here exists to
;; make startup fast.  The frame keeps stock Emacs' chrome (menu bar,
;; tool bar, scroll bars) and startup screen, as GNU Emacs has them.
;; Nothing in here should depend on a third-party package.

;;; Code:

;; `--init-directory', `keymap-set' and `defvar-keymap' are all 29.1+.
(when (< emacs-major-version 29)
  (error "Hell Emacs needs Emacs 29.1 or newer; this is %s" emacs-version))

;; On Windows, Emacs may find no HOME, and put ~ somewhere unexpected.
(let (realhome)
  (when (and (memq system-type '(cygwin windows-nt ms-dos))
             (null (getenv-internal "HOME"))
             (setq realhome (getenv "USERPROFILE")))
    (setenv "HOME" realhome)
    (setq abbreviated-home-dir nil)))

;;; 1. Directory layout --------------------------------------------
;;
;; Defined here, first, because both the performance tuning below
;; and every file loaded after this one need to know where things live.
;;
;; Hell Emacs keeps three kinds of files apart, following Doom Emacs and
;; the XDG base directory spec:
;;
;;   `hell-dir'       the distribution itself (this git repo)
;;   `hell-user-dir'  your config: init.el, config.el, custom.el
;;   `hell-data-dir'  installed packages -- needed to run, but
;;                        regenerated by reinstalling
;;   `hell-cache-dir' disposable: native-comp output, caches
;;   `hell-state-dir' history, recent files, bookmarks, backups --
;;                        not essential, but can't be regenerated
;;
;; A named profile (`emacs --profile work', or HELL_PROFILE=work)
;; gets a completely separate set of all four: ~/.config/hell-emacs-work/,
;; ~/.local/share/hell-emacs-work/, and so on. The same Hell Emacs checkout
;; can then run several independent configs side by side.

(defconst hell-dir
  (file-name-directory (file-truename (or load-file-name buffer-file-name)))
  "Root directory of the Hell Emacs distribution.")

(defconst hell-core-dir (expand-file-name "lisp/" hell-dir)
  "Directory holding Hell Emacs' core: lisp/, as Doom v3's `doom-core-dir'.
Its library is in lib/ and the CLI's parts in cli/ (see `hell-require').")

(defconst hell-modules-dir (expand-file-name "modules/" hell-dir)
  "Hell Emacs' own modules/: core's module, hell/ (Doom v3's modules/doom/).")

(defconst hell-sources-dir (expand-file-name "sources/" hell-dir)
  "Directory of module sources, each holding a modules/ tree.
The catalog is hell+/,
in this repository (Doom v3's sources/doom+/, a submodule there).")

(defconst hell-profile
  (let ((name (or (cadr (member "--profile" command-line-args))
                  (getenv-internal "HELL_PROFILE"))))
    (unless (member name '(nil "" "default"))
      (unless (string-match-p "\\`[A-Za-z0-9_-]+\\'" name)
        (error "Invalid Hell Emacs profile name %S (use letters, digits, - and _)" name))
      name))
  "Name of the active profile, or nil for the default one.
Set with `emacs --profile NAME' or the HELL_PROFILE environment
variable (which `bin/hell --profile NAME' sets). Each profile has
its own config, packages, caches and history.")

;; Emacs doesn't know --profile; consume it (and its value) so it isn't
;; treated as a file to open.
(push (cons "--profile" (lambda (_) (pop command-line-args-left))) command-switch-alist)

(defconst hell--dir-name
  (if hell-profile (concat "hell-emacs-" hell-profile) "hell-emacs")
  "Name of Hell Emacs' directories under ~/.config, ~/.local/share, etc.")

(defun hell--xdg-dir (envvar fallback)
  "Return Hell Emacs' subdirectory of $ENVVAR, or of FALLBACK if unset."
  (expand-file-name (concat hell--dir-name "/") (or (getenv-internal envvar) fallback)))

(defun hell--read-profiles-el (dir)
  "Read explicit profile definitions from profiles.el in DIR, if present.
Returns an alist of (NAME . PLIST)."
  (let ((file (expand-file-name "profiles.el" dir))
        profiles)
    (when (file-exists-p file)
      (with-temp-buffer
        (insert-file-contents file)
        (goto-char (point-min))
        (condition-case err
            (while (not (eobp))
              (let ((form (read (current-buffer))))
                (pcase form
                  (`(profile! ,name . ,plist)
                   (push (cons (if (symbolp name) (symbol-name name) name) plist) profiles))
                  (`(setq hell-profiles ',list)
                   (dolist (item list)
                     (push (cons (if (symbolp (car item)) (symbol-name (car item)) (car item))
                                 (cdr item))
                           profiles)))
                  ((and (pred consp) (guard (symbolp (car form))))
                   (push (cons (symbol-name (car form)) (cdr form)) profiles)))))
          ;; How reading every form ends.
          (end-of-file nil)
          ;; A typo: the profiles before it count, and you're told.
          (error (display-warning
                  'hell (format "%s can't be read past line %d (%s); profiles after it are ignored"
                                (abbreviate-file-name file) (line-number-at-pos)
                                (error-message-string err)))))))
    (nreverse profiles)))

(defun hell--user-dir (profile)
  "The config directory of PROFILE (nil for the default one).
$HELLDIR if set. Else, for the default profile, the first of
~/.config/hell-emacs/ (under $XDG_CONFIG_HOME) and ~/.hell-emacs.d/ that
exists, ~/.config/hell-emacs/ if neither. For a named one, checks explicit
profiles in profiles.el, then the first of ~/.config/hell-emacs-NAME/, your
config's profiles/NAME/ and Hell Emacs' profiles/NAME/ that exists (Doom v3's
implicit profiles), else ~/.config/hell-emacs-NAME/."
  (let ((config (or (getenv-internal "XDG_CONFIG_HOME") "~/.config")))
    (if-let* ((dir (getenv-internal "HELLDIR")))
        (file-name-as-directory (expand-file-name dir))
      (let ((xdg (expand-file-name "hell-emacs/" config)))
        (if (null profile)
            (cond ((and (boundp 'hell-dir)
                        (file-regular-p (expand-file-name "init.el" hell-dir))
                        (not (file-symlink-p (expand-file-name "init.el" hell-dir))))
                   hell-dir)
                  ((file-directory-p xdg) xdg)
                  ((file-directory-p "~/.hell-emacs.d/") (expand-file-name "~/.hell-emacs.d/"))
                  (t xdg))
          (let* ((default-dir (if (or (file-directory-p xdg) (not (file-directory-p "~/.hell-emacs.d/")))
                                  xdg
                                (expand-file-name "~/.hell-emacs.d/")))
                 (explicit (hell--read-profiles-el default-dir))
                 (entry (cdr (assoc (if (symbolp profile) (symbol-name profile) profile) explicit))))
            (if-let* ((custom-dir (or (plist-get entry :user-dir) (plist-get entry :config-dir))))
                (file-name-as-directory (expand-file-name custom-dir))
              (let ((own (expand-file-name (format "hell-emacs-%s/" profile) config)))
                (catch 'found
                  (dolist (dir (list own
                                     (expand-file-name (format "profiles/%s/" profile) default-dir)
                                     (expand-file-name (format "profiles/%s/" profile) hell-dir)))
                    (when (file-directory-p dir) (throw 'found dir)))
                  own)))))))))

(defvar hell-user-dir (hell--user-dir hell-profile)
  "Your private configuration: init.el, config.el and custom.el.
See `hell--user-dir' for where it is: ~/.config/hell-emacs/ by
default, and for a named profile ~/.config/hell-emacs-NAME/, or a
profiles/NAME/ directory. It's fine for it not to exist -- Hell Emacs
then runs with its defaults. See `hell-init-user-dir'.")

(defconst hell-team-dir
  (let ((env (getenv-internal "HELL_TEAM_DIR")))
    (cond (env (file-name-as-directory (expand-file-name env)))
          ((file-directory-p (expand-file-name "team/" hell-user-dir))
           (file-name-as-directory (expand-file-name "team/" hell-user-dir)))
          (t nil)))
  "Directory containing shared enterprise team configuration, or nil.")

(defconst hell-data-dir (hell--xdg-dir "XDG_DATA_HOME" "~/.local/share")
  "Installed packages and other data Hell Emacs needs to run.
Deleting it forces every package to be reinstalled on the next start.")

(defconst hell-cache-dir (hell--xdg-dir "XDG_CACHE_HOME" "~/.cache")
  "Disposable, regenerable files: native-comp output and package caches.
Safe to delete at any time.")

(defconst hell-state-dir (hell--xdg-dir "XDG_STATE_HOME" "~/.local/state")
  "History, recent files, bookmarks, undo history, backups and autosaves.
Not needed to run, but deleting it loses that history for good.")

(defconst hell-profile-dir
  (expand-file-name (format "profiles/%s/" (or hell-profile "default")) hell-data-dir)
  "Where `bin/hell sync' writes the generated profile.")

(defconst hell-compiled-dir (expand-file-name "compiled/" hell-profile-dir)
  "Where `bin/hell sync' byte-compiles core and the enabled modules' config.
Kept per profile, and away from the sources: a module's compiled config
depends on the profile (the packages it declares or disables).")

(defun hell-compiled-core-current-p ()
  "Non-nil if the core compiled by the last sync matches core's sources.
That is: this Emacs compiled it, and no lisp/**/*.el changed since. Cheap
enough for every startup (three directory listings and a few stats)."
  (let ((stamp (expand-file-name "lisp/stamp" hell-compiled-dir)))
    (and (file-exists-p stamp)
         (equal (with-temp-buffer (insert-file-contents stamp) (buffer-string))
                emacs-version)
         (catch 'changed
           (dolist (file (directory-files-recursively hell-core-dir "\\.el\\'") t)
             (when (file-newer-than-file-p file stamp)
               (throw 'changed nil)))))))

(defvar hell--initial-load-path (copy-sequence load-path)
  "`load-path' before Hell Emacs or any package touched it: Emacs' own.
Used to tell whether a package is built into Emacs (`package!'s
:built-in \\='prefer).")

(define-obsolete-variable-alias 'hell-var-dir 'hell-cache-dir "0.2")
(define-obsolete-variable-alias 'hell-etc-dir 'hell-state-dir "0.2")

(with-file-modes #o700
  (dolist (dir (list hell-data-dir hell-cache-dir hell-state-dir))
    (unless (file-directory-p dir)
      (make-directory dir t))))

;;; 2. Startup performance: GC ---------------------------------------
;;
;; Emacs runs a GC check on every allocation, which adds up over the
;; hundreds of `require'/`load' calls a full startup performs. Raise
;; the threshold as high as possible for the duration of boot;
;; `hell-core' (lisp/hell-core.el) restores a bounded runtime value once startup
;; finishes (see `hell--restore-gc-h' there).

(defvar hell--gc-cons-threshold (* 16 1024 1024)
  "GC threshold Hell Emacs restores once startup completes.")
(defvar hell--gc-cons-percentage 0.1
  "GC percentage Hell Emacs restores once startup completes.")

(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 1.0)

;;; 3. Startup performance: file-name-handler-alist -------------------
;;
;; Consulted on every `require'/`load'/`expand-file-name' call to
;; check for TRAMP, compressed, or encrypted file names. Trimming it
;; during boot skips that check for the hundreds of local elisp files
;; Hell Emacs loads at startup. (Skipped for the daemon, where startup
;; time matters less.)
;;
;; The gzip handler has to stay if this Emacs ships its own Lisp
;; compressed (some distributions do): libraries that exist only as
;; .el.gz couldn't be loaded otherwise. Emacs' Lisp is either all
;; compressed or not, so one file tells which.

(defvar hell--file-name-handler-alist (copy-sequence file-name-handler-alist)
  "`file-name-handler-alist' as Emacs set it up, before Hell Emacs trimmed it.")

(unless (daemonp)
  (setq file-name-handler-alist
        (unless (locate-file-internal "calc-loaddefs.el" load-path)
          (list (rassq 'jka-compr-handler hell--file-name-handler-alist))))

  ;; Files named on the command line are opened during startup and may
  ;; be remote (TRAMP) or compressed, so they get the full list back.
  (define-advice command-line-1 (:around (fn args-left) hell-file-handlers)
    (let ((file-name-handler-alist
           (if args-left hell--file-name-handler-alist file-name-handler-alist)))
      (funcall fn args-left)))

  ;; Restore it for the session, merging rather than overwriting in case
  ;; something added a handler during startup.
  (add-hook 'emacs-startup-hook
            (lambda ()
              (advice-remove #'command-line-1 #'command-line-1@hell-file-handlers)
              (setq file-name-handler-alist
                    (delete-dups (append file-name-handler-alist
                                         (copy-sequence hell--file-name-handler-alist)))))
            101))

;;; 4. package.el: disabled in favor of Elpaca -------------------------
;;
;; Hell Emacs bootstraps Elpaca itself (see `hell-packages'). Letting
;; `package.el' also initialize at startup would scan and autoload a
;; redundant, conflicting package system for no benefit.

(setq package-enable-at-startup nil)

;;; 5. Native compilation ----------------------------------------------

;; The `native-compile' feature is present even when native compilation
;; can't actually work (e.g. libgccjit is missing). Some packages then
;; try to use it anyway; pretend it doesn't exist instead.
(when (and (featurep 'native-compile)
           (not (native-comp-available-p)))
  (setq features (delq 'native-compile features)))

(when (featurep 'native-compile)
  ;; Redirect .eln files out of `user-emacs-directory'/eln-cache (the
  ;; git checkout) and into the cache dir: they're regenerable, and
  ;; `hell-cache-dir' stays the one thing that's always safe to
  ;; delete.
  (when (fboundp 'startup-redirect-eln-cache)
    (startup-redirect-eln-cache (expand-file-name "eln/" hell-cache-dir)))
  ;; Compile asynchronously instead of blocking the editor, and don't
  ;; pop up a warnings buffer for every third-party package that trips
  ;; a (usually harmless) native-comp warning during first compile.
  (setq native-comp-async-report-warnings-errors 'silent
        native-comp-jit-compilation t
        native-comp-async-jobs-number
        (max 1 (if (fboundp 'num-processors) (/ (num-processors) 2) 2))))

;;; 6. UI: GNU Emacs' own frame and startup screen ----------------------
;;
;; Unlike Doom, the frame keeps stock Emacs' chrome -- menu bar, tool
;; bar, scroll bars, tooltips -- and Emacs' own startup screen and echo
;; area message (13.4): the layout is GNU Emacs', the look Hell Emacs'.
;; modules/hell/+splash.el themes the startup screen; a user who wants
;; less turns the stock modes off in their config.el.

(setq initial-scratch-message nil
      inhibit-default-init t
      ;; Resizing the frame to match font metrics on every startup and
      ;; theme load is a measurable, avoidable cost; do it once.
      frame-inhibit-implied-resize t)

;;; 7. Miscellaneous startup and runtime settings -----------------------

;; `auto-mode-alist' is matched a second, case-insensitive time when
;; the first pass fails -- time wasted on every file opened. It only
;; requires patterns (and file names) to be properly cased.
(setq auto-mode-case-fold nil)

;; Warnings about packages redefining functions with the legacy advice
;; API aren't actionable, and each one triggers a redisplay.
(setq ad-redefinition-action 'accept)

;; Read subprocess output in 64KB chunks instead of 4KB. Language
;; servers and REPLs send a lot of it.
(setq read-process-output-max (* 64 1024))

;; Emacs 31 warns about every package file lacking a `lexical-binding'
;; cookie; users can't act on that for third-party packages.
(add-to-list 'warning-inhibit-types '(files missing-lexbind-cookie))

;; DEBUG=1 as an alternative to --debug-init, e.g. for bin/hell:
;; more logging (`hell-log') and backtraces on errors.
(when (member (getenv-internal "DEBUG") '("1" "t" "true" "yes"))
  (setq init-file-debug t
        debug-on-error t))

;; Site-wide defaults (site-start.el, default.el) almost always either
;; duplicate or actively conflict with a config as opinionated as a
;; full distribution's.
(setq site-run-file nil)


;;; 8. Startup hacks, undone once the init file has loaded ------------------
;;
;; As Doom's early-init.el: skip work Emacs does during startup that a
;; synced Hell Emacs doesn't need, or that it does again anyway.

(unless (or (daemonp) noninteractive init-file-debug)
  ;; "Loading ..." messages, and the stock mode-line, flash for a moment
  ;; while modules load; hide both until the init file is done.
  (put 'mode-line-format 'initial-value (default-toplevel-value 'mode-line-format))
  (setq-default mode-line-format nil)
  (dolist (buf (buffer-list))
    (with-current-buffer buf (setq mode-line-format nil)))
  (setq-default inhibit-message t)
  ;; In a terminal, set it up once the frame is, not before.
  (unless initial-window-system
    (define-advice tty-run-terminal-initialization (:override (&rest _) hell-defer)
      (advice-remove #'tty-run-terminal-initialization
                     #'tty-run-terminal-initialization@hell-defer)
      (add-hook 'window-setup-hook
                (apply-partially #'tty-run-terminal-initialization (selected-frame) nil t))))
  (define-advice startup--load-user-init-file (:around (fn &rest args) hell-undo-hacks 95)
    "Undo early-init.el's startup hacks, once the init file has loaded."
    (unwind-protect (apply fn args)
      (setq-default inhibit-message nil)
      (unless (default-toplevel-value 'mode-line-format)
        (setq-default mode-line-format (get 'mode-line-format 'initial-value)))))
  ;; Command-line options for other window systems than this one.
  (unless (eq system-type 'darwin)
    (setq command-line-ns-option-alist nil))
  (unless (memq initial-window-system '(x pgtk))
    (setq command-line-x-option-alist nil)))

;;; 9. Core: loaded here, as Doom's early-init.el loads lisp/doom.el ----------
;;
;; As in Doom v3, Hell Emacs has no init.el of its own. Core loads here
;; (byte-compiled, when the last sync compiled it and it hasn't changed
;; since), and `hell-initialize' sets it up. Interactively, core's
;; entry point (lisp/hell-emacs.el) then replaces Emacs' init file
;; loading: it loads the profile's init file, which `bin/hell sync'
;; generates (lisp/hell-profiles.el), and runs the startup it holds.

(add-to-list 'load-path hell-core-dir)

(defvar hell--compiled-core-p (hell-compiled-core-current-p)
  "Non-nil if core was loaded byte-compiled, from `hell-compiled-dir'.
All of it, or none: compiled files carry each other's macros.")
(when hell--compiled-core-p
  (add-to-list 'load-path (expand-file-name "lisp/" hell-compiled-dir)))

(require 'hell-core)
(hell-initialize (not noninteractive))

(provide 'early-init)
;;; early-init.el ends here
