;;; early-init.el --- Hellmacs early initialization -*- lexical-binding: t; no-byte-compile: t; -*-

;; Copyright (C) 2026 petrolal <petrolalucas@gmail.com>
;;
;; Author: petrolal <petrolalucas@gmail.com>
;; URL: https://github.com/petrolal/hellmacs
;; License: GPL-3.0-or-later
;;
;; This file is part of Hellmacs.
;;
;; Hellmacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; Hellmacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;; This file is loaded before `package.el', before `init.el', and
;; before the first frame is created.  Everything here exists to
;; make startup fast and to keep the first frame from flashing
;; stock Emacs chrome before Hellmacs gets a chance to configure it.
;; Nothing in here should depend on a third-party package.

;;; Code:

;; `--init-directory', `keymap-set' and `defvar-keymap' are all 29.1+.
(when (< emacs-major-version 29)
  (error "Hellmacs needs Emacs 29.1 or newer; this is %s" emacs-version))

;; On Windows, Emacs may find no HOME, and put ~ somewhere unexpected.
(let (realhome)
  (when (and (memq system-type '(cygwin windows-nt ms-dos))
             (null (getenv-internal "HOME"))
             (setq realhome (getenv "USERPROFILE")))
    (setenv "HOME" realhome)
    (setq abbreviated-home-dir nil)))

;;; 1. Directory layout --------------------------------------------
;;
;; Defined here, first, because both the performance tuning below
;; and every file loaded after this one need to know where things live.
;;
;; Hellmacs keeps three kinds of files apart, following Doom Emacs and
;; the XDG base directory spec:
;;
;;   `hellmacs-dir'       the distribution itself (this git repo)
;;   `hellmacs-user-dir'  your config: init.el, config.el, custom.el
;;   `hellmacs-data-dir'  installed packages -- needed to run, but
;;                        regenerated by reinstalling
;;   `hellmacs-cache-dir' disposable: native-comp output, caches
;;   `hellmacs-state-dir' history, recent files, bookmarks, backups --
;;                        not essential, but can't be regenerated
;;
;; A named profile (`emacs --profile work', or HELLMACS_PROFILE=work)
;; gets a completely separate set of all four: ~/.config/hellmacs-work/,
;; ~/.local/share/hellmacs-work/, and so on. The same Hellmacs checkout
;; can then run several independent configs side by side.

(defconst hellmacs-dir
  (file-name-directory (file-truename (or load-file-name buffer-file-name)))
  "Root directory of the Hellmacs distribution.")

(defconst hellmacs-core-dir (expand-file-name "lisp/" hellmacs-dir)
  "Directory holding Hellmacs' core: lisp/, as Doom v3's `doom-core-dir'.
Its library is in lib/ and the CLI's parts in cli/ (see `hellmacs-require').")

(defconst hellmacs-modules-dir (expand-file-name "modules/" hellmacs-dir)
  "Hellmacs' own modules/: core's module, hellmacs/ (Doom v3's modules/doom/).")

(defconst hellmacs-sources-dir (expand-file-name "sources/" hellmacs-dir)
  "Module sources: each holds a modules/ tree. The catalog is hellmacs+/,
in this repository (Doom v3's sources/doom+/, a submodule there).")

(defconst hellmacs-profile
  (let ((name (or (cadr (member "--profile" command-line-args))
                  (getenv-internal "HELLMACS_PROFILE"))))
    (unless (member name '(nil "" "default"))
      (unless (string-match-p "\\`[A-Za-z0-9_-]+\\'" name)
        (error "Invalid Hellmacs profile name %S (use letters, digits, - and _)" name))
      name))
  "Name of the active profile, or nil for the default one.
Set with `emacs --profile NAME' or the HELLMACS_PROFILE environment
variable (which `bin/hellmacs --profile NAME' sets). Each profile has
its own config, packages, caches and history.")

;; Emacs doesn't know --profile; consume it (and its value) so it isn't
;; treated as a file to open.
(push (cons "--profile" (lambda (_) (pop command-line-args-left))) command-switch-alist)

(defconst hellmacs--dir-name
  (if hellmacs-profile (concat "hellmacs-" hellmacs-profile) "hellmacs")
  "Name of Hellmacs' directories under ~/.config, ~/.local/share, etc.")

(defun hellmacs--xdg-dir (envvar fallback)
  "Return Hellmacs' subdirectory of $ENVVAR, or of FALLBACK if unset."
  (expand-file-name (concat hellmacs--dir-name "/") (or (getenv-internal envvar) fallback)))

(defun hellmacs--read-profiles-el (dir)
  "Read explicit profile definitions from profiles.el in DIR, if present.
Returns an alist of (NAME . PLIST)."
  (let ((file (expand-file-name "profiles.el" dir))
        profiles)
    (when (file-exists-p file)
      (with-temp-buffer
        (insert-file-contents file)
        (goto-char (point-min))
        (condition-case nil
            (while (not (eobp))
              (let ((form (read (current-buffer))))
                (pcase form
                  (`(profile! ,name . ,plist)
                   (push (cons (if (symbolp name) (symbol-name name) name) plist) profiles))
                  (`(setq hellmacs-profiles ',list)
                   (dolist (item list)
                     (push (cons (if (symbolp (car item)) (symbol-name (car item)) (car item))
                                 (cdr item))
                           profiles)))
                  ((and (pred consp) (guard (symbolp (car form))))
                   (push (cons (symbol-name (car form)) (cdr form)) profiles)))))
          (error nil))))
    (nreverse profiles)))

(defun hellmacs--user-dir (profile)
  "The config directory of PROFILE (nil for the default one).
$HELLMACSDIR if set. Else, for the default profile, the first of
~/.config/hellmacs/ (under $XDG_CONFIG_HOME) and ~/.hellmacs.d/ that
exists, ~/.config/hellmacs/ if neither. For a named one, checks explicit
profiles in profiles.el, then the first of ~/.config/hellmacs-NAME/, your
config's profiles/NAME/ and Hellmacs' profiles/NAME/ that exists (Doom v3's
implicit profiles), else ~/.config/hellmacs-NAME/."
  (let ((config (or (getenv-internal "XDG_CONFIG_HOME") "~/.config")))
    (if-let* ((dir (getenv-internal "HELLMACSDIR")))
        (file-name-as-directory (expand-file-name dir))
      (let ((xdg (expand-file-name "hellmacs/" config)))
        (if (null profile)
            (if (or (file-directory-p xdg) (not (file-directory-p "~/.hellmacs.d/")))
                xdg
              (expand-file-name "~/.hellmacs.d/"))
          (let* ((default-dir (if (or (file-directory-p xdg) (not (file-directory-p "~/.hellmacs.d/")))
                                  xdg
                                (expand-file-name "~/.hellmacs.d/")))
                 (explicit (hellmacs--read-profiles-el default-dir))
                 (entry (cdr (assoc (if (symbolp profile) (symbol-name profile) profile) explicit))))
            (if-let* ((custom-dir (or (plist-get entry :user-dir) (plist-get entry :config-dir))))
                (file-name-as-directory (expand-file-name custom-dir))
              (let ((own (expand-file-name (format "hellmacs-%s/" profile) config)))
                (catch 'found
                  (dolist (dir (list own
                                     (expand-file-name (format "profiles/%s/" profile) default-dir)
                                     (expand-file-name (format "profiles/%s/" profile) hellmacs-dir)))
                    (when (file-directory-p dir) (throw 'found dir)))
                  own)))))))))

(defvar hellmacs-user-dir (hellmacs--user-dir hellmacs-profile)
  "Your private configuration: init.el, config.el and custom.el.
See `hellmacs--user-dir' for where it is: ~/.config/hellmacs/ by
default, and for a named profile ~/.config/hellmacs-NAME/, or a
profiles/NAME/ directory. It's fine for it not to exist -- Hellmacs
then runs with its defaults. See `hellmacs-init-user-dir'.")

(defconst hellmacs-data-dir (hellmacs--xdg-dir "XDG_DATA_HOME" "~/.local/share")
  "Installed packages and other data Hellmacs needs to run.
Deleting it forces every package to be reinstalled on the next start.")

(defconst hellmacs-cache-dir (hellmacs--xdg-dir "XDG_CACHE_HOME" "~/.cache")
  "Disposable, regenerable files: native-comp output and package caches.
Safe to delete at any time.")

(defconst hellmacs-state-dir (hellmacs--xdg-dir "XDG_STATE_HOME" "~/.local/state")
  "History, recent files, bookmarks, undo history, backups and autosaves.
Not needed to run, but deleting it loses that history for good.")

(defconst hellmacs-profile-dir
  (expand-file-name (format "profiles/%s/" (or hellmacs-profile "default")) hellmacs-data-dir)
  "Where `bin/hellmacs sync' writes the generated profile.")

(defconst hellmacs-compiled-dir (expand-file-name "compiled/" hellmacs-profile-dir)
  "Where `bin/hellmacs sync' byte-compiles core and the enabled modules' config.
Kept per profile, and away from the sources: a module's compiled config
depends on the profile (the packages it declares or disables).")

(defun hellmacs-compiled-core-current-p ()
  "Non-nil if the core compiled by the last sync matches core's sources.
That is: this Emacs compiled it, and no lisp/**/*.el changed since. Cheap
enough for every startup (three directory listings and a few stats)."
  (let ((stamp (expand-file-name "lisp/stamp" hellmacs-compiled-dir)))
    (and (file-exists-p stamp)
         (equal (with-temp-buffer (insert-file-contents stamp) (buffer-string))
                emacs-version)
         (catch 'changed
           (dolist (file (directory-files-recursively hellmacs-core-dir "\\.el\\'") t)
             (when (file-newer-than-file-p file stamp)
               (throw 'changed nil)))))))

(defvar hellmacs--initial-load-path (copy-sequence load-path)
  "`load-path' before Hellmacs or any package touched it: Emacs' own.
Used to tell whether a package is built into Emacs (`package!'s
:built-in \='prefer).")

(define-obsolete-variable-alias 'hellmacs-var-dir 'hellmacs-cache-dir "0.2")
(define-obsolete-variable-alias 'hellmacs-etc-dir 'hellmacs-state-dir "0.2")

(with-file-modes #o700
  (dolist (dir (list hellmacs-data-dir hellmacs-cache-dir hellmacs-state-dir))
    (unless (file-directory-p dir)
      (make-directory dir t))))

;;; 2. Startup performance: GC ---------------------------------------
;;
;; Emacs runs a GC check on every allocation, which adds up over the
;; hundreds of `require'/`load' calls a full startup performs. Raise
;; the threshold as high as possible for the duration of boot;
;; `hellmacs' (lisp/hellmacs.el) restores a bounded runtime value once startup
;; finishes (see `hellmacs--restore-gc-h' there).

(defvar hellmacs--gc-cons-threshold (* 16 1024 1024)
  "GC threshold Hellmacs restores once startup completes.")
(defvar hellmacs--gc-cons-percentage 0.1
  "GC percentage Hellmacs restores once startup completes.")

(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 1.0)

;;; 3. Startup performance: file-name-handler-alist -------------------
;;
;; Consulted on every `require'/`load'/`expand-file-name' call to
;; check for TRAMP, compressed, or encrypted file names. Trimming it
;; during boot skips that check for the hundreds of local elisp files
;; Hellmacs loads at startup. (Skipped for the daemon, where startup
;; time matters less.)
;;
;; The gzip handler has to stay if this Emacs ships its own Lisp
;; compressed (some distributions do): libraries that exist only as
;; .el.gz couldn't be loaded otherwise. Emacs' Lisp is either all
;; compressed or not, so one file tells which.

(defvar hellmacs--file-name-handler-alist (copy-sequence file-name-handler-alist)
  "`file-name-handler-alist' as Emacs set it up, before Hellmacs trimmed it.")

(unless (daemonp)
  (setq file-name-handler-alist
        (unless (locate-file-internal "calc-loaddefs.el" load-path)
          (list (rassq 'jka-compr-handler hellmacs--file-name-handler-alist))))

  ;; Files named on the command line are opened during startup and may
  ;; be remote (TRAMP) or compressed, so they get the full list back.
  (define-advice command-line-1 (:around (fn args-left) hellmacs-file-handlers)
    (let ((file-name-handler-alist
           (if args-left hellmacs--file-name-handler-alist file-name-handler-alist)))
      (funcall fn args-left)))

  ;; Restore it for the session, merging rather than overwriting in case
  ;; something added a handler during startup.
  (add-hook 'emacs-startup-hook
            (lambda ()
              (advice-remove #'command-line-1 #'command-line-1@hellmacs-file-handlers)
              (setq file-name-handler-alist
                    (delete-dups (append file-name-handler-alist
                                         (copy-sequence hellmacs--file-name-handler-alist)))))
            101))

;;; 4. package.el: disabled in favor of Elpaca -------------------------
;;
;; Hellmacs bootstraps Elpaca itself (see `hellmacs-packages'). Letting
;; `package.el' also initialize at startup would scan and autoload a
;; redundant, conflicting package system for no benefit.

(setq package-enable-at-startup nil)

;;; 5. Native compilation ----------------------------------------------

;; The `native-compile' feature is present even when native compilation
;; can't actually work (e.g. libgccjit is missing). Some packages then
;; try to use it anyway; pretend it doesn't exist instead.
(when (and (featurep 'native-compile)
           (not (native-comp-available-p)))
  (setq features (delq 'native-compile features)))

(when (featurep 'native-compile)
  ;; Redirect .eln files out of `user-emacs-directory'/eln-cache (the
  ;; git checkout) and into the cache dir: they're regenerable, and
  ;; `hellmacs-cache-dir' stays the one thing that's always safe to
  ;; delete.
  (when (fboundp 'startup-redirect-eln-cache)
    (startup-redirect-eln-cache (expand-file-name "eln/" hellmacs-cache-dir)))
  ;; Compile asynchronously instead of blocking the editor, and don't
  ;; pop up a warnings buffer for every third-party package that trips
  ;; a (usually harmless) native-comp warning during first compile.
  (setq native-comp-async-report-warnings-errors 'silent
        native-comp-jit-compilation t
        native-comp-async-jobs-number
        (max 1 (if (fboundp 'num-processors) (/ (num-processors) 2) 2))))

;;; 6. UI: unset chrome before the first frame is drawn -----------------
;;
;; Setting these as frame parameters (rather than calling
;; `menu-bar-mode' etc. later from `init.el') avoids allocating the
;; widgets in the first place. That is both faster and prevents the
;; "flash" of a fully-chromed default frame before Hellmacs' own
;; config has a chance to run.

(setq default-frame-alist
      (append '((menu-bar-lines . 0)
                (tool-bar-lines . 0)
                (vertical-scroll-bars . nil)
                (horizontal-scroll-bars . nil))
              default-frame-alist))

;; Belt-and-suspenders: also set the minor-mode variables so a later
;; `make-frame' (e.g. a new frame opened mid-session) stays consistent
;; even if something toggles a mode instead of touching frame params.
(setq menu-bar-mode nil
      tool-bar-mode nil
      scroll-bar-mode nil
      tooltip-mode nil)

(setq inhibit-startup-screen t
      inhibit-startup-echo-area-message user-login-name
      initial-scratch-message nil
      inhibit-default-init t
      ;; Resizing the frame to match font metrics on every startup and
      ;; theme load is a measurable, avoidable cost; do it once.
      frame-inhibit-implied-resize t)

;; `inhibit-startup-echo-area-message' only works when set literally in
;; the user's init file, and even with `inhibit-startup-screen' Emacs
;; still does some of the splash screen's work. Skip both outright.
(unless (daemonp)
  (advice-add #'display-startup-echo-area-message :override #'ignore)
  (advice-add #'display-startup-screen :override #'ignore))

;;; 7. Miscellaneous startup and runtime settings -----------------------

;; `auto-mode-alist' is matched a second, case-insensitive time when
;; the first pass fails -- time wasted on every file opened. It only
;; requires patterns (and file names) to be properly cased.
(setq auto-mode-case-fold nil)

;; Warnings about packages redefining functions with the legacy advice
;; API aren't actionable, and each one triggers a redisplay.
(setq ad-redefinition-action 'accept)

;; Read subprocess output in 64KB chunks instead of 4KB. Language
;; servers and REPLs send a lot of it.
(setq read-process-output-max (* 64 1024))

;; Emacs 31 warns about every package file lacking a `lexical-binding'
;; cookie; users can't act on that for third-party packages.
(add-to-list 'warning-inhibit-types '(files missing-lexbind-cookie))

;; DEBUG=1 as an alternative to --debug-init, e.g. for bin/hellmacs:
;; more logging (`hellmacs-log') and backtraces on errors.
(when (member (getenv-internal "DEBUG") '("1" "t" "true" "yes"))
  (setq init-file-debug t
        debug-on-error t))

;; Site-wide defaults (site-start.el, default.el) almost always either
;; duplicate or actively conflict with a config as opinionated as a
;; full distribution's.
(setq site-run-file nil)


;;; 8. Startup hacks, undone once the init file has loaded ------------------
;;
;; As Doom's early-init.el: skip work Emacs does during startup that a
;; synced Hellmacs doesn't need, or that it does again anyway.

(unless (or (daemonp) noninteractive init-file-debug)
  ;; "Loading ..." messages, and the stock mode-line, flash for a moment
  ;; while modules load; hide both until the init file is done.
  (put 'mode-line-format 'initial-value (default-toplevel-value 'mode-line-format))
  (setq-default mode-line-format nil)
  (dolist (buf (buffer-list))
    (with-current-buffer buf (setq mode-line-format nil)))
  (setq-default inhibit-message t)
  ;; Setting up a tool bar Hellmacs has turned off is expensive; do it only
  ;; if something turns `tool-bar-mode' on.
  (advice-add #'tool-bar-setup :override #'ignore)
  ;; In a terminal, set it up once the frame is, not before.
  (unless initial-window-system
    (define-advice tty-run-terminal-initialization (:override (&rest _) hellmacs-defer)
      (advice-remove #'tty-run-terminal-initialization
                     #'tty-run-terminal-initialization@hellmacs-defer)
      (add-hook 'window-setup-hook
                (apply-partially #'tty-run-terminal-initialization (selected-frame) nil t))))
  (define-advice startup--load-user-init-file (:around (fn &rest args) hellmacs-undo-hacks 95)
    "Undo early-init.el's startup hacks, once the init file has loaded."
    (unwind-protect (apply fn args)
      (setq-default inhibit-message nil)
      (advice-remove #'tool-bar-setup #'ignore)
      (define-advice tool-bar-mode (:after (&rest _) hellmacs-setup)
        (advice-remove #'tool-bar-mode #'tool-bar-mode@hellmacs-setup)
        (tool-bar-setup))
      (unless (default-toplevel-value 'mode-line-format)
        (setq-default mode-line-format (get 'mode-line-format 'initial-value)))))
  ;; Command-line options for other window systems than this one.
  (unless (eq system-type 'darwin)
    (setq command-line-ns-option-alist nil))
  (unless (memq initial-window-system '(x pgtk))
    (setq command-line-x-option-alist nil)))

;;; 9. Core: loaded here, as Doom's early-init.el loads lisp/doom.el ----------
;;
;; As in Doom v3, Hellmacs has no init.el of its own. Core loads here
;; (byte-compiled, when the last sync compiled it and it hasn't changed
;; since), and `hellmacs-initialize' sets it up. Interactively, core's
;; entry point (lisp/hellmacs-emacs.el) then replaces Emacs' init file
;; loading: it loads the profile's init file, which `bin/hellmacs sync'
;; generates (lisp/hellmacs-profiles.el), and runs the startup it holds.

(add-to-list 'load-path hellmacs-core-dir)

(defvar hellmacs--compiled-core-p (hellmacs-compiled-core-current-p)
  "Non-nil if core was loaded byte-compiled, from `hellmacs-compiled-dir'.
All of it, or none: compiled files carry each other's macros.")
(when hellmacs--compiled-core-p
  (add-to-list 'load-path (expand-file-name "lisp/" hellmacs-compiled-dir)))

(require 'hellmacs)
(hellmacs-initialize (not noninteractive))

(provide 'early-init)
;;; early-init.el ends here
