;;; lisp/lib/check-report.el --- The quality gate's reports -*- lexical-binding: t; -*-

;; Copyright (C) 2026 petrolal <petrolalucas@gmail.com>
;;
;; Author: petrolal <petrolalucas@gmail.com>
;; URL: https://github.com/petrolal/hell-emacs
;; License: GPL-3.0-or-later
;;
;; This file is part of Hell Emacs.
;;
;; Hell Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; Hell Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.


;;; Commentary:

;; The report `bin/hell check' writes: Markdown (the default,
;; .hell/reports/lint-report.md) or JSON, from `hell-check-run-all''s
;; results.
;;
;; Part `check-report' of `hell-lib': (hell-require 'hell-lib 'check-report).

;;; Code:

(require 'cl-lib)
(require 'subr-x)
(require 'json)
(require 'hell-lib)

(defvar hell-check-languages)           ; lib/check-tools.el

;;; Automated Report Generation -----------------------------------------------

(defun hell-check-format-markdown (results)
  "Format RESULTS as a Markdown diagnostic report."
  (let* ((timestamp (plist-get results :timestamp))
         (targets (plist-get results :targets))
         (tools (plist-get results :tools))
         (files-count (plist-get results :total-files))
         (errors (plist-get results :errors))
         (warnings (plist-get results :warnings))
         (info (plist-get results :info))
         (total (+ errors warnings info))
         (diags (plist-get results :diagnostics)))
    (with-temp-buffer
      (insert "# Static Analysis and Linting Quality Gate Report\n\n")
      (insert (format "- **Execution Timestamp:** `%s`\n" timestamp))
      (insert (format "- **Target Paths:** `%s`\n" (mapconcat #'identity targets ", ")))
      (insert (format "- **Tools Invoked:** %s\n\n"
                      (if tools
                          (mapconcat (lambda (t-name) (format "`%s`" t-name)) tools ", ")
                        "None")))

      (insert "## Summary\n\n")
      (insert (format "- **Total Scanned Files:** %d\n" files-count))
      (insert (format "- **Total Issues:** %d\n" total))
      (insert (format "  - **Error:** %d\n" errors))
      (insert (format "  - **Warning:** %d\n" warnings))
      (insert (format "  - **Info:** %d\n\n" info))

      (insert "## Breakdown\n\n")
      (insert "| Language | Tool | Severity | Location (file:line:col) | Rule ID | Message |\n")
      (insert "|:---|:---|:---|:---|:---|:---|\n")
      (if (null diags)
          (insert "\n*No issues detected across all scanned files. Quality gate passed!*\n")
        (dolist (d diags)
          (let ((lang (plist-get d :language))
                (tool (plist-get d :tool))
                (sev (plist-get d :severity))
                (loc (plist-get d :location))
                (rule (plist-get d :rule-id))
                (msg (replace-regexp-in-string "|" "\\\\|" (plist-get d :message))))
            (insert (format "| %s | %s | %s | `%s` | `%s` | %s |\n"
                            lang tool sev loc rule msg)))))
      (insert "\n---\n*Report generated by Hell Emacs Quality Gate.*\n")
      (buffer-string))))

(defun hell-check-format-json (results)
  "Format RESULTS as a JSON diagnostic report."
  (let* ((timestamp (plist-get results :timestamp))
         (targets (plist-get results :targets))
         (tools (plist-get results :tools))
         (files-count (plist-get results :total-files))
         (errors (plist-get results :errors))
         (warnings (plist-get results :warnings))
         (info (plist-get results :info))
         (total (+ errors warnings info))
         (diags (plist-get results :diagnostics))
         (issues (mapcar (lambda (d)
                           (list (cons "language" (plist-get d :language))
                                 (cons "tool" (plist-get d :tool))
                                 (cons "severity" (plist-get d :severity))
                                 (cons "location" (plist-get d :location))
                                 (cons "file" (plist-get d :file))
                                 (cons "line" (plist-get d :line))
                                 (cons "col" (plist-get d :col))
                                 (cons "rule_id" (plist-get d :rule-id))
                                 (cons "message" (plist-get d :message))))
                         diags))
         (tree (list (cons "timestamp" timestamp)
                     (cons "target_paths" (vconcat targets))
                     (cons "tools_invoked" (vconcat tools))
                     (cons "summary" (list (cons "total_scanned_files" files-count)
                                           (cons "total_issues" total)
                                           (cons "errors" errors)
                                           (cons "warnings" warnings)
                                           (cons "info" info)))
                     (cons "breakdown" (vconcat issues)))))
    (let ((json-encoding-pretty-print t))
      (json-encode tree))))

(defun hell-check-write-report (results output-path format-type)
  "Write RESULTS to OUTPUT-PATH using FORMAT-TYPE (`markdown' or `json')."
  (let* ((out (expand-file-name output-path))
         (dir (file-name-directory out))
         (content (if (eq format-type 'json)
                      (hell-check-format-json results)
                    (hell-check-format-markdown results))))
    (when dir
      (make-directory dir t))
    (with-temp-file out
      (insert content (if (string-suffix-p "\n" content) "" "\n")))
    out))


(hell-provide 'hell-lib 'check-report)
;;; check-report.el ends here
