;;; hellmacs-profiles.el --- The profile's generated init file -*- lexical-binding: t; -*-

;; Copyright (C) 2026 petrolal <petrolalucas@gmail.com>
;;
;; Author: petrolal <petrolalucas@gmail.com>
;; URL: https://github.com/petrolal/hellmacs
;; License: GPL-3.0-or-later
;;
;; This file is part of Hellmacs.
;;
;; Hellmacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; Hellmacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;; As Doom v3's lisp/doom-profiles.el: `bin/hellmacs sync' generates the
;; profile's init file, <profile>/init.el, byte-compiled, and early-init.el
;; hands Emacs that one (`hellmacs-init-file'). Hellmacs has no init.el of
;; its own. The file is numbered parts, as Doom's is:
;;
;;   05-hellmacs.init.el        what sync knows: core is compiled, and where
;;   10-hellmacs-start.init.el  lisp/hellmacs-start.el's forms: the startup
;;
;; lisp/hellmacs-start.el is also what loads, from source, while there's no
;; generated file or it's out of date, so the startup is written once.

;;; Code:

(defvar hellmacs-profile-dir)  ; early-init.el
(defvar hellmacs-compiled-dir) ; early-init.el
(defvar hellmacs-core-dir)     ; early-init.el
(defvar hellmacs-profile)      ; early-init.el

(defun hellmacs-profile-init-file ()
  "The profile's generated init file: <profile>/init.el."
  (expand-file-name "init.el" hellmacs-profile-dir))

(defun hellmacs-profile--start-forms ()
  "The text of lisp/hellmacs-start.el's forms: after its Code: line, up to
its `provide'."
  (with-temp-buffer
    (insert-file-contents (expand-file-name "hellmacs-start.el" hellmacs-core-dir))
    (goto-char (point-min))
    (re-search-forward "^;;; Code:\n")
    (buffer-substring (point) (progn (re-search-forward "^(provide 'hellmacs-start)")
                                     (match-beginning 0)))))

(defun hellmacs-profile-delete-init ()
  "Delete the generated init file (and its compiled form), if there is one."
  (dolist (file (list (hellmacs-profile-init-file) (concat (hellmacs-profile-init-file) "c")))
    (when (file-exists-p file) (delete-file file))))

(defun hellmacs-profile-generate-init ()
  "Write the profile's init file and byte-compile it; return its name.
Only after core compiled: part 05 says so, and puts it on `load-path'."
  (let ((file (hellmacs-profile-init-file))
        (byte-compile-warnings nil))
    (make-directory hellmacs-profile-dir t)
    (with-temp-file file
      (insert ";;; init.el --- Generated by `bin/hellmacs sync'; don't edit -*- lexical-binding: t; -*-\n"
              (format ";; Profile: %s. Hellmacs %s. See lisp/hellmacs-profiles.el.\n\n"
                      (or hellmacs-profile "default") hellmacs-version)
              ";;; 05-hellmacs.init.el\n\n"
              "(defvar hellmacs--compiled-core-p t)\n"
              (format "(add-to-list 'load-path %S)\n" hellmacs-core-dir)
              (format "(add-to-list 'load-path %S)\n\n"
                      (expand-file-name "lisp/" hellmacs-compiled-dir))
              ";;; 10-hellmacs-start.init.el (lisp/hellmacs-start.el)\n\n"
              (hellmacs-profile--start-forms)
              ";;; init.el ends here\n"))
    (byte-compile-file file)
    file))

(provide 'hellmacs-profiles)
;;; hellmacs-profiles.el ends here
