;;; hell-emacs.el --- Stock Emacs, with saner defaults -*- lexical-binding: t; -*-

;; Copyright (C) 2026 petrolal <petrolalucas@gmail.com>
;;
;; Author: petrolal <petrolalucas@gmail.com>
;; URL: https://github.com/petrolal/hell-emacs
;; License: GPL-3.0-or-later
;;
;; This file is part of Hell Emacs.
;;
;; Hell Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; Hell Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;; The stock settings Hell Emacs changes, in every session (Doom v3's
;; lisp/doom-emacs.el). Loaded right after hell-core.el.

;;; Code:

;;; Sane global defaults --------------------------------------------------

(setq-default indent-tabs-mode nil
              tab-width 4
              fill-column 80
              cursor-in-non-selected-windows nil)

(setq ring-bell-function #'ignore
      visible-bell nil
      create-lockfiles nil           ; TRAMP/CI mostly; local editing rarely needs them
      load-prefer-newer t
      sentence-end-double-space nil
      require-final-newline t
      help-window-select t           ; jump straight into *Help* buffers
      delete-by-moving-to-trash t
      large-file-warning-threshold (* 50 1024 1024))

(require 'autorevert)
(setq global-auto-revert-non-file-buffers t
      auto-revert-avoid-polling t)     ; file notifications, not a 5s stat of every buffer
(global-auto-revert-mode 1)
;; The two departures from stock behaviour (docs/keybindings.md): typing
;; replaces the region, and brackets and quotes come in pairs.
(delete-selection-mode 1)
(electric-pair-mode 1)

(set-language-environment "UTF-8")
(set-default-coding-systems 'utf-8)
(prefer-coding-system 'utf-8)

(setq frame-title-format
      (if (and (boundp 'hell-profile) hell-profile)
          (list (format "Hell Emacs [%s] — " hell-profile) '(buffer-file-name "%f" "%b"))
        (list "Hell Emacs — " '(buffer-file-name "%f" "%b"))))

;;; Entry point -----------------------------------------------------------
;;
;; As in Doom's doom-emacs.el, this takes over Emacs' init file loader:
;;
;;   1. it loads the profile's init file, generated by `bin/hell sync'
;;      (`hell-start'), instead of looking for one;
;;   2. so ~/.emacs, ~/_emacs and an init.el in this checkout are never
;;      loaded, and never searched for;
;;   3. and an error there leaves you a working Emacs, saying what to do.

(define-advice startup--load-user-init-file (:override (&rest _) hell-init 100)
  "Start Hell Emacs from the profile's init file (`hell-start')."
  (let ((debug-on-error (or debug-on-error (and init-file-debug t)))
        ;; A byte-compiled init file may hold NULs (Emacs bug#52554).
        (inhibit-null-byte-detection t))
    (when init-file-user
      (condition-case-unless-debug err
          (progn
            (hell-start)
            (setq user-init-file (hell-init-file)))
        (hell-nosync-error
         (setq init-file-had-error t)
         (display-warning 'hell (format "Hell Emacs can't start: %s.\n\
Until then, this is plain Emacs." (cadr err))
                          :error))
        (error
         (setq init-file-had-error t)
         (display-warning
          'initialization
          (format "An error occurred while starting Hell Emacs:\n\n%s\n\n\
Start Emacs with --debug-init (or DEBUG=1) to see where. To start without
your config and modules: `bin/hell -p safe-mode sync', then
`bin/hell -p safe-mode emacs'."
                  (error-message-string err))
          :error))))))

(provide 'hell-emacs)
;;; hell-emacs.el ends here
